set -e
set -x

make clean
make main-optimized

INTERPOLATION=0 INTUNIFORM=1e3 ./main-optimized
INTERPOLATION=0 INTUNIFORM=1e4 ./main-optimized
INTERPOLATION=0 INTUNIFORM=1e5 ./main-optimized
INTERPOLATION=0 INTUNIFORM=1e6 ./main-optimized
INTERPOLATION=0 INTUNIFORM=1e7 ./main-optimized
INTERPOLATION=0 INTUNIFORM=5e7 ./main-optimized


INTERPOLATION=0 BYTE=1e3 BYTESIZE=8 ./main-optimized
INTERPOLATION=0 BYTE=1e3 BYTESIZE=32 ./main-optimized
INTERPOLATION=0 BYTE=1e3 BYTESIZE=128 ./main-optimized
INTERPOLATION=0 BYTE=1e4 BYTESIZE=8 ./main-optimized
INTERPOLATION=0 BYTE=1e4 BYTESIZE=32 ./main-optimized
INTERPOLATION=0 BYTE=1e4 BYTESIZE=128 ./main-optimized
INTERPOLATION=0 BYTE=1e5 BYTESIZE=8 ./main-optimized
INTERPOLATION=0 BYTE=1e5 BYTESIZE=32 ./main-optimized
INTERPOLATION=0 BYTE=1e5 BYTESIZE=128 ./main-optimized
INTERPOLATION=0 BYTE=1e6 BYTESIZE=8 ./main-optimized
INTERPOLATION=0 BYTE=1e6 BYTESIZE=32 ./main-optimized
INTERPOLATION=0 BYTE=1e6 BYTESIZE=128 ./main-optimized
INTERPOLATION=0 BYTE=1e7 BYTESIZE=8 ./main-optimized
INTERPOLATION=0 BYTE=1e7 BYTESIZE=32 ./main-optimized
INTERPOLATION=0 BYTE=1e7 BYTESIZE=128 ./main-optimized