set -e
set -x

make clean
make main-optimized

INTERPOLATION=0 INTLITTLEENDIAN=1e6 ./main-optimized #MISSING
INTERPOLATION=0 INTLITTLEENDIAN=1e7 ./main-optimized #MISSING
INTERPOLATION=0 INTLITTLEENDIAN=2e7 ./main-optimized #MISSING
INTERPOLATION=0 INTLITTLEENDIAN=3e7 ./main-optimized #MISSING
INTERPOLATION=0 INTLITTLEENDIAN=4e7 ./main-optimized #MISSING
INTERPOLATION=0 INTLITTLEENDIAN=5e7 ./main-optimized #MISSING