./binarySearchNoPrefix4KB.sh > binarySearchNoPrefix4KB-lauf1.txt
./binarySearch4KB.sh > binarySearch4KB-lauf2.text
./binarySearchNoPrefix4KB.sh > binarySearchNoPrefix4KB-lauf2.txt
./binarySearch4KB.sh > binarySearch4KB-lauf3.text
./binarySearchNoPrefix4KB.sh > binarySearchNoPrefix4KB-lauf3.txt
./binarySearchHints4KB.sh > binarySearchHints4KB-lauf1.txt
./linearSearch4KB.sh > linearSearch4KB.txt
./binarySearchHints4KB.sh > binarySearchHints4KB-lauf2.txt
./binarySearchHints4KB.sh > binarySearchHints4KB-lauf3.txt
./MAP > map.txt